server:
  port: ${SERVER_PORT:8092}

ai-search:
  index-name: ${AI_SEARCH_ES_INDEX:food-products-e5-small-ko}
  read-alias: ${AI_SEARCH_ES_READ_ALIAS:food-products-e5-small-ko-read}
  embedding-model-path: ${AI_SEARCH_EMBED_MODEL_PATH:classpath:/model/multilingual-e5-small-ko}
