server:
  port: ${SERVER_PORT:8094}

ai-search:
  index-name: ${AI_SEARCH_ES_INDEX:food-products-minilm-l6}
  read-alias: ${AI_SEARCH_ES_READ_ALIAS:food-products-minilm-l6-read}
  embedding-model-path: ${AI_SEARCH_EMBED_MODEL_PATH:classpath:/model/minilm-l6}
