CREATE TABLE IF NOT EXISTS model_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_key VARCHAR(100) NOT NULL,
    search_query VARCHAR(500) NOT NULL,
    score INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_model_feedback_model_query
    ON model_feedback (model_key, search_query);
