package com.example.aisearch.service.feedback;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

@Repository
public class ModelFeedbackRepository {

    private final JdbcTemplate jdbcTemplate;
    private volatile boolean schemaInitialized;

    public ModelFeedbackRepository(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    public void save(String modelKey, String query, int score) {
        ensureSchema();
        jdbcTemplate.update(
                "insert into model_feedback (model_key, search_query, score) values (?, ?, ?)",
                modelKey,
                query,
                score
        );
    }

    public ModelFeedbackSummary summarize(String modelKey, String query) {
        ensureSchema();
        return jdbcTemplate.queryForObject(
                """
                select model_key,
                       search_query,
                       coalesce(avg(score), 0) as average_score,
                       count(*) as rating_count
                  from model_feedback
                 where model_key = ?
                   and search_query = ?
                 group by model_key, search_query
                """,
                (rs, rowNum) -> new ModelFeedbackSummary(
                        rs.getString("model_key"),
                        rs.getString("search_query"),
                        rs.getDouble("average_score"),
                        rs.getLong("rating_count")
                ),
                modelKey,
                query
        );
    }

    public ModelFeedbackOverallSummary summarizeOverall(String modelKey) {
        ensureSchema();
        return jdbcTemplate.queryForObject(
                """
                select model_key,
                       coalesce(avg(score), 0) as average_score,
                       count(*) as rating_count
                  from model_feedback
                 where model_key = ?
                 group by model_key
                """,
                (rs, rowNum) -> new ModelFeedbackOverallSummary(
                        rs.getString("model_key"),
                        rs.getDouble("average_score"),
                        rs.getLong("rating_count")
                ),
                modelKey
        );
    }

    private void ensureSchema() {
        if (schemaInitialized) {
            return;
        }

        synchronized (this) {
            if (schemaInitialized) {
                return;
            }
            initializeSchema();
            schemaInitialized = true;
        }
    }

    private void initializeSchema() {
        jdbcTemplate.execute("""
                create table if not exists model_feedback (
                    id bigint generated by default as identity primary key,
                    model_key varchar(100) not null,
                    search_query varchar(500) not null,
                    score int not null,
                    created_at timestamp default current_timestamp not null
                )
                """);

        jdbcTemplate.execute("""
                create index if not exists idx_model_feedback_model_query
                on model_feedback (model_key, search_query)
                """);
    }
}
